### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bpr4110**

### CODE REVIEW

**Comment by Niabubu** [comment]
Sorry I do not understand that what description do I need to upload

**Comment by bpr4110** [comment]
Which part are u talking about?

**Comment by bpr4110** [comment]
What's going on? 😂

**Comment by Niabubu** [comment]
When will it merge??

**Comment by bpr4110** [comment]
@Niabubu I am interested why u didn't merge
or cannot merge?
Basically after u approved u can directly merge it
Just like what @ecxcxcx did

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
